events { worker_connections 1024; }
http {
    underscores_in_headers on; 
        server {
            listen 80;

            location / {
                proxy_pass http://localhost:4094/api/v1/products;
                proxy_set_header Upgrade $httP_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }

            location =/shopping/webhook {
                proxy_pass http://localhost:4095/api/v1/shopping/webhook;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;                
            }

            location ~ ^/shopping {
                rewrite ^/shopping(?:/(.*))?$ /api/v1/shopping/$1 break;
                auth_request /verify;
                auth_request_set $user $upstream_http_x_user;
                proxy_set_header X-User $user;
                proxy_pass http://localhost:4095;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }

            

            location ~ ^/admin {
                rewrite ^/admin(?:/(.*)) /api/v1/products/$1 break;
                auth_request /verify;
                auth_request_set $user $upstream_http_x_user;
                proxy_set_header X-User $user;
                proxy_pass http://localhost:4092;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }

            # location = /users/login {
            #     proxy_pass http://localhost:4093/api/v1/users/login;
            #     proxy_set_header Upgrade $http_upgrade;
            #     proxy_set_header Connection 'upgrade';
            #     proxy_set_header Host $host;
            #     proxy_cache_bypass $httP_upgrade;
            # }

            # location = /users/signup {
            #     proxy_pass http://localhost:4093/api/v1/users/signup;
            #     proxy_set_header Upgrade $http_upgrade;
            #     proxy_set_header Connection 'upgrade';
            #     proxy_set_header Host $host;
            #     proxy_cache_bypass $httP_upgrade;
            # }

            location /users {
                location = /users/verify {
                    return 403;
                }

                rewrite ^/users(?:/(.*))?$ /api/v1/users/$1 break;
                proxy_pass http://localhost:4093;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }

            location =/verify {
                internal;
                proxy_method GET;
                proxy_pass http://127.0.0.1:4093/api/v1/users/verify;
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";
                proxy_set_header X-Original-URI $request_uri;

            }
        }
}