// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from 'fs'
import path from 'path'
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getSecret(secretName: string) {
  try {
    // Docker mounts secrets to /run/secrets/ by default
    const secretPath = path.join('/run/secrets', secretName);
    return fs.readFileSync(secretPath, 'utf8').trim();
  } catch (err) {
    // Fallback to environment variables for local development flexibility
    return process.env[secretName]; 
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getSecret("PRODUCT_DATABASE_URL") as string,
  },
});
